feat: added Controller of User
GiuseppeCorrao/Flow_Open_Spring pull request #12
Opened 2022-10-20 11:02 UTC by samueleCatalano

2022-10-20 15:34 UTC, GiuseppeCorrao commented on src/main/resources/application.yml
> +    url: jdbc:mysql://127.0.0.1:3306/flowopendev
questa parte di codice non c'entra nulla con la PR, rimuovi questo file

2022-10-20 15:35 UTC, GiuseppeCorrao requested changes
rivedi il codice tramite linee guida -> commenti

2022-10-20 15:45 UTC, samueleCatalano commented on src/main/resources/application.yml
> +    url: jdbc:mysql://127.0.0.1:3306/flowopendev
e come lo rimuovo?

2022-10-22 12:18 UTC, GiuseppeCorrao commented on src/main/java/develhope/Flow_Open_Spring/controller/UserController.java
> +    @DeleteMapping("/{id}")
in teoria sono sbagliati i status perchè non è un conflitto se non trova l'id ma è un 404 not found

2022-10-22 12:21 UTC, GiuseppeCorrao requested changes
sistema gli status, e mergiamo, aggiungi un else if se necessario e al 3 statement ovvero l'else metti conflict ma prima di questo dovresti inserire notfound se non trova l'id

2022-10-25 08:29 UTC, merged