add file README
GiuseppeCorrao/Flow_Open_Spring pull request #14
Opened 2022-10-21 08:12 UTC by francoforte123

2022-10-21 10:21 UTC, samueleCatalano commented
devi scrivere tutto in inglese

2022-10-21 10:21 UTC, samueleCatalano requested changes
scrivi tutto in inglese

2022-10-21 10:22 UTC, samueleCatalano commented on README.md
> +
e java

2022-10-21 13:26 UTC, francoforte123 commented
Si lo so che va fatto in inglese, a me serve semplicemente se l'impostazione è buona o no

2022-10-21 13:31 UTC, francoforte123 commented on README.md
> +
Si si, me lo sono dimenticato

2022-10-22 12:16 UTC, GiuseppeCorrao requested changes
aggiungi una parte in cui andremo a mettere le richieste API e anche i link per la documentazione

2022-10-22 12:18 UTC, francoforte123 commented
Okay pè

2022-10-24 15:00 UTC, samueleCatalano requested changes
come contenuti più o meno ci siamo, ma secondo me puoi essere ancora un po' più esplicativo. non dico di spiegare ogni riga di codice, ma secondo me va aggiunto anche altro sulle altre classi e funzioni.

2022-10-24 16:08 UTC, francoforte123 commented
Va bene Samuè!, vediamo cosa dicono anche gli altri colleghi, caso mai si aggiungono in seguito

2022-10-25 08:25 UTC, GiuseppeCorrao requested changes
creare sezione per la documentazione

2022-10-26 08:08 UTC, merged