feat: added logging
GiuseppeCorrao/Flow_Open_Spring pull request #21
Opened 2022-10-31 10:07 UTC by samueleCatalano

2022-11-03 18:47 UTC, GiuseppeCorrao commented
ci sono dei conflitti samu risolvili

2022-11-03 18:51 UTC, GiuseppeCorrao commented on src/main/java/develhope/Flow_Open_Spring/controller/CartController.java
>      public double totalPrice(){
non vedo il log di questo metodo

2022-11-03 18:53 UTC, GiuseppeCorrao commented on src/main/java/develhope/Flow_Open_Spring/controller/ProductController.java
> +            Error error = new Error("no products in the db");
è giusto creare tutte queste entità per il logger.info ? cerchiamo di ottimizzare usa semplicemente il logger con un testo

2022-11-03 18:56 UTC, GiuseppeCorrao commented on src/main/resources/application.yml
>      hibernate:
non hai aggiunto il folder del log, hai creato la cartella in resource ?

2022-11-03 18:56 UTC, GiuseppeCorrao commented on src/main/java/develhope/Flow_Open_Spring/controller/CartController.java
>      ProductRepository productRepository;
l'indentazione con il codice sopra

2022-11-03 18:59 UTC, GiuseppeCorrao requested changes
leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml.  In più stai usando slf4j per il logger.

2022-11-03 20:00 UTC, samueleCatalano commented
> leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml. In più stai usando slf4j per il logger.



> leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml. In più stai usando slf4j per il logger.

in che senso sto usando slf4j? il file di configurazione è di logback

2022-11-03 20:04 UTC, samueleCatalano commented
> leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml. In più stai usando slf4j per il logger.

poi non ho capito a che ti riferisci col fatto della path, non mi ricordo sta cosa nel video. forse ti confondi col file upload?

2022-11-04 17:41 UTC, GiuseppeCorrao commented
> > leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml. In più stai usando slf4j per il logger.
> 
> > leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml. In più stai usando slf4j per il logger.
> 
> in che senso sto usando slf4j? il file di configurazione è di logback 
guarda negli import non usi logback ma slf4

2022-11-04 17:42 UTC, GiuseppeCorrao commented
> > leggi i commenti, hai creato il file log ?,se si devi mettere la path sul file yml. In più stai usando slf4j per il logger.
> 
> poi non ho capito a che ti riferisci col fatto della path, non mi ricordo sta cosa nel video. forse ti confondi col file upload?

non mi sto confondendo, i log vanno salvati in un file e per referenziare questo file si usa l'application.yml ovviamente lo devi creare, ti consiglio di riguardare il video

2022-11-09 07:33 UTC, francoforte123 commented
mi sembra buono

2022-11-11 09:09 UTC, merged